# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32330d05d87508bd22b63e448fbe6ef8d74aba18d738dac4b9ffafaba6723f0ec238f5f9fd1387d12965c727125fb61883bc7d6271c41cf4b1f5b68ea0bd2289

test:
  secret_key_base: 514ae6b00bb6e51a79dd16613e550ec6572fe683035231e097f625547f198d046ae96e878795cd1bb8f5938a3d87ec0dd50772c60c7915737400d8a1911dc08c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
